// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

/** Native gameplay tags used by the combat simulation and its data. */
namespace CombatTags
{
	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status);
	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Taunted);

	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect);
	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Taunt);
	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Slow);
	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Rally);

	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue);
	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Fire);
	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Cleave);
	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Rally);
	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cue_Taunt);

	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim);
	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Hit);
	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Death);
	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Throw);
	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Push);
	BATTLESYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Anim_Punch);
}
