"""Imports Mixamo animations (FBX) and retargets them to the hero skeleton.

Run headless with the editor closed:
    UnrealEditor-Cmd.exe BattleSystem.uproject -run=pythonscript -script="<abs path>/Scripts/ImportMixamoAnimations.py" -unattended -nullrhi -nosplash

Every .fbx in SOURCE_DIR is imported as an animation on the Mixamo skeleton into RAW_PATH, then retargeted with RETARGETER
from SOURCE_MESH to TARGET_MESH (SKEL_Hero) into TARGET_PATH. Subfolders are mirrored (Walk/X.fbx -> Mixamo/Walk/X and
Heroes/Walk/X); files directly in SOURCE_DIR go to RAW_PATH and TARGET_PATH/ROOT_SUBFOLDER. Names come from the file name,
cleaned ("Rifle Idle (1)" -> Rifle_Idle_1), or from ALIASES. Animations whose retargeted asset already exists are skipped,
so the script can run again after every download. Root motion is turned off on the results (the simulation moves the units).
For each new animation the log says whether it is in place; one that is not (its hips travel) needs "In Place" on Mixamo.
"""

import os
import re

import unreal

LOG_TAG = "[MixamoImport]"
SOURCE_DIR = "D:/Unreal/Assets/Animations"
RAW_PATH = "/Game/Characters/Animations/Mixamo"
TARGET_PATH = "/Game/Characters/Animations/Heroes"
ROOT_SUBFOLDER = "Combat"
MIXAMO_SKELETON = "/Game/Characters/Animations/Mixamo/SKEL_Mixamo"
SOURCE_MESH = "/Game/Characters/Animations/Mixamo/SKM_Mixamo"
TARGET_MESH = "/Game/Characters/Animations/Heroes/SKM_Hero_Male"
RETARGETER = "/Game/Characters/Animations/Heroes/RTG_AutoGenerated"
HIPS_BONE = "Hips"
# File name (without .fbx) -> asset name, for files whose asset got another name before.
ALIASES = {
    "Throw": "Throw_Anim",
}
# Suffix of the retargeted copies before they move to TARGET_PATH (so they never clash with the raw ones).
TEMP_SUFFIX = "_RetargetTemp"


def log(message):
    unreal.log(f"{LOG_TAG} {message}")


def clean_name(file_stem):
    if file_stem in ALIASES:
        return ALIASES[file_stem]
    name = re.sub(r"[^A-Za-z0-9_]+", "_", file_stem)
    return re.sub(r"_+", "_", name).strip("_")


def find_sources():
    """(fbx path, raw folder, target folder, asset name) for every .fbx, sorted."""
    sources = []
    for folder, _, files in os.walk(SOURCE_DIR):
        relative = os.path.relpath(folder, SOURCE_DIR).replace("\\", "/")
        subfolder = "" if relative == "." else relative
        raw_folder = f"{RAW_PATH}/{subfolder}" if subfolder else RAW_PATH
        target_folder = f"{TARGET_PATH}/{subfolder if subfolder else ROOT_SUBFOLDER}"
        for file_name in sorted(files):
            stem, extension = os.path.splitext(file_name)
            if extension.lower() == ".fbx":
                sources.append((os.path.join(folder, file_name).replace("\\", "/"), raw_folder, target_folder, clean_name(stem)))
    return sorted(sources)


def import_animation(fbx_path, raw_folder, name, skeleton):
    """Imports one FBX as an animation on the Mixamo skeleton; returns the AnimSequence or None."""
    options = unreal.FbxImportUI()
    options.set_editor_property("import_mesh", False)
    options.set_editor_property("import_animations", True)
    options.set_editor_property("import_as_skeletal", True)
    options.set_editor_property("import_materials", False)
    options.set_editor_property("import_textures", False)
    options.set_editor_property("skeleton", skeleton)
    options.set_editor_property("mesh_type_to_import", unreal.FBXImportType.FBXIT_ANIMATION)
    anim_data = options.get_editor_property("anim_sequence_import_data")
    anim_data.set_editor_property("import_uniform_scale", 1.0)
    anim_data.set_editor_property("animation_length", unreal.FBXAnimationLengthImportType.FBXALIT_EXPORTED_TIME)

    task = unreal.AssetImportTask()
    task.set_editor_property("filename", fbx_path)
    task.set_editor_property("destination_path", raw_folder)
    task.set_editor_property("destination_name", name)
    task.set_editor_property("automated", True)
    task.set_editor_property("replace_existing", False)
    task.set_editor_property("save", True)
    task.set_editor_property("options", options)
    unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])

    for path in task.get_editor_property("imported_object_paths") or []:
        asset = unreal.load_asset(path)
        if isinstance(asset, unreal.AnimSequence):
            return asset
    return None


def hips_speed(anim):
    """Horizontal distance the hips travel over the animation, per second (0 for an in-place animation)."""
    length = unreal.AnimationLibrary.get_sequence_length(anim)
    if length <= 0.0:
        return 0.0
    start = unreal.AnimationLibrary.get_bone_pose_for_time(anim, HIPS_BONE, 0.0, False)
    end = unreal.AnimationLibrary.get_bone_pose_for_time(anim, HIPS_BONE, length, False)
    delta = end.translation - start.translation
    return (delta.x ** 2 + delta.y ** 2) ** 0.5 / length


def main():
    lib = unreal.EditorAssetLibrary
    for path in [MIXAMO_SKELETON, SOURCE_MESH, TARGET_MESH, RETARGETER]:
        if not lib.does_asset_exist(path):
            log(f"ABORT: {path} not found")
            return
    skeleton = unreal.load_asset(MIXAMO_SKELETON)
    source_mesh = unreal.load_asset(SOURCE_MESH)
    target_mesh = unreal.load_asset(TARGET_MESH)
    retargeter = unreal.load_asset(RETARGETER)

    # The classic FBX importer, so FbxImportUI's settings apply (UE 5.8 imports FBX through Interchange by default).
    unreal.SystemLibrary.execute_console_command(None, "Interchange.FeatureFlags.Import.FBX 0")

    to_retarget = []
    skipped = 0
    for fbx_path, raw_folder, target_folder, name in find_sources():
        if lib.does_asset_exist(f"{target_folder}/{name}"):
            skipped += 1
            continue
        raw_path = f"{raw_folder}/{name}"
        anim = unreal.load_asset(raw_path) if lib.does_asset_exist(raw_path) else import_animation(fbx_path, raw_folder, name, skeleton)
        if not anim:
            log(f"FAILED to import {fbx_path}")
            continue
        if anim.get_path_name().split(".")[0] != raw_path:
            log(f"Imported {fbx_path} as {anim.get_path_name()} (expected {raw_path})")
        to_retarget.append((anim, target_folder, name))

    log(f"{skipped} already retargeted, {len(to_retarget)} to retarget")
    if not to_retarget:
        log("Done")
        return

    asset_data = [lib.find_asset_data(anim.get_path_name()) for anim, _, _ in to_retarget]
    # Copies next to their source (with TEMP_SUFFIX); moved to their target folder below.
    results = unreal.IKRetargetBatchOperation.duplicate_and_retarget(
        asset_data, source_mesh, target_mesh, retargeter, suffix=TEMP_SUFFIX, use_source_path=True,
        include_referenced_assets=False)
    by_name = {str(data.asset_name): data for data in results or []}

    created = []
    for anim, target_folder, name in to_retarget:
        data = by_name.get(f"{anim.get_name()}{TEMP_SUFFIX}")
        if not data:
            log(f"FAILED to retarget {anim.get_path_name()}")
            continue
        target_path = f"{target_folder}/{name}"
        if not lib.rename_asset(str(data.package_name), target_path):
            log(f"FAILED to move {data.package_name} to {target_path}")
            continue
        retargeted = unreal.load_asset(target_path)
        retargeted.set_editor_property("enable_root_motion", False)
        lib.save_loaded_asset(retargeted, False)
        created.append(name)
        travel = hips_speed(anim)
        log(f"Created {target_path}" + (f" - NOT in place: the hips travel {travel:.0f} cm/s" if travel > 5.0 else ""))

    log(f"New animations ({len(created)}): {', '.join(created)}")
    log("Done")


main()
